#!/usr/bin/env sh

icon="$HOME/.xlock/icon.png"
if [ $UID -eq 0 ]; then
    tmpbg='/tmp/rscr.png'
else
    tmpbg='/tmp/screen.png'
fi

scrot "$tmpbg"
convert "$tmpbg" -scale 10% -scale 1000% "$tmpbg"
#convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
rm $tmpbg
